[package]
name = "task1"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.13.2", features = ["serde", "ecdsa"] }
rand = "0.8.5"
sha2 = "0.10.8"
serde = "1.0"
serde_json = "1.0"
